name: Auxiliary

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Octokit
        run: npm install @octokit/core

      - name: Get Latest Commit ID
        id: get_commit
        run: echo "commit_id=${{ github.sha }}" >> $GITHUB_ENV

      - name: Add Code Suggestions Comments
        env:
          COMMIT_ID: ${{ github.sha }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          commit_id=${{ env.COMMIT_ID }}
          
          const [owner, repo] =  ${{ github.repository }}.split('/');
          await github.rest.pulls.createReview({
            owner: owner,
            repo: repo,
            pull_number:  ${{ github.event.number }}
            commit_id: '${{ github.sha }}',
            event: 'REQUEST_CHANGES',
            comments: 'hello'
          });
          # node post-comments.js "hello" "$commit_id" "goodbye.py" "1" "RIGHT"
