name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sudo -E sh

    - name: Start Ollama Service
      run: |
        nohup ollama serve &

        sleep 5
        curl -i http://localhost:11434

    - name: Pull Llama3 Model
      run: |
        ollama pull llama3

    - name: Install dependencies
      run: |
        pip install requests openai python-dotenv pygithub litellm

    - name: Run code review script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python .github/scripts/code_review.py
