name: GPT Code Review

on:
  workflow_dispatch:

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sudo -E sh

      - name: Start Ollama Service
        run: |
          nohup ollama serve &

          sleep 5
          curl -i http://localhost:11434

      - name: Pull Llama3 Model
        run: |
          ollama pull llama3

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install litellm openai python-dotenv PyGithub

      - name: Run Code Review Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        run: python .github/scripts/code_review.py
