name: Setup Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
      
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sudo -E sh

    - name: Start Ollama Service
      run: |
        nohup ollama serve &
        sleep 5
        curl -i http://localhost:11434

    - name: Pull Llama3 Model
      run: |
        ollama pull llama3

    - name: Cache Python Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install litellm openai python-dotenv
        pip freeze > requirements.txt

    - name: Verify Python Dependencies
      run: |
        python3 -m pip show litellm
        python3 -m pip show openai
        python3 -m pip show python-dotenv

    - name: Run Python Script
      run: |
        changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
        python3 chatbot.py "$changed_files"
        cat reviews.txt
