name: GPT Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sudo -E sh

      - name: Start Ollama Service
        run: |
          nohup ollama serve &

          sleep 5
          curl -i http://localhost:11434

      - name: Pull Llama3 Model
        run: |
          ollama pull llama3

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install litellm openai python-dotenv

      - name: Fetch Base Branch
        run: git fetch origin main:main

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: List All Changed Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Create Diffs Directory
        run: mkdir -p diffs

      - name: Get File Diffs
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Generating diffs for: $changed_files"
          for file in $changed_files; do
            git diff origin/main -- $file > diffs/$file.diff
          done

      - name: Run Python Script
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Running chatbot.py with files: $changed_files"
          python3 chatbot.py "$changed_files"
          cat script_output.txt

      - name: Parse and Output Reviews
        id: parse-output
        run: |
          reviews=""
          file=""
          review=""
          while IFS= read -r line; do
            if [[ "$line" == "FILE:"* ]]; then
              if [[ ! -z "$file" ]]; then
                reviews="$reviews\n$file=$review"
              fi
              file=$(echo $line | cut -d' ' -f2)
              review=""
            elif [[ "$line" == "REVIEW:"* ]]; then
              review=$(echo $line | cut -d' ' -f2-)
            elif [[ "$line" == "ENDREVIEW" ]]; then
              reviews="$reviews\n$file=$review"
              file=""
              review=""
            else
              review="$review\n$line"
            fi
          done < script_output.txt
          if [[ ! -z "$file" ]]; then
            reviews="$reviews\n$file=$review"
          fi
          echo -e "$reviews" > reviews.txt
          cat reviews.txt

      - name: Get Latest Commit ID
        id: get_commit
        run: echo "commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Add Code Suggestions Comments
        run: |
          commit_id=${{ env.commit_id }}
          cat reviews.txt | while read -r line; do
            file=$(echo $line | cut -d= -f1)
            review=$(echo $line | cut -d= -f2-)
            diff_file="diffs/$file.diff"
            if [ -f "$diff_file" ]; then
              # Extract the first diff hunk
              diff_hunk=$(awk '/^@@/ {print; exit}' "$diff_file")
              # Find the line position of the first change
              position=$(awk '/^@@/ {print NR+1; exit}' "$diff_file")
              echo "Posting review for $file at position $position"
              echo "Commit ID: $commit_id"
              echo "Diff hunk: $diff_hunk"
              echo "Review: $review"
              curl -s -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/comments \
                -d "$(jq -n --arg body "$review" --arg path "$file" --argjson position $position --arg commit_id "$commit_id" --arg diff_hunk "$diff_hunk" '{body: $body, path: $path, position: $position, commit_id: $commit_id, diff_hunk: $diff_hunk}')"
            fi
          done
