name: GPT Code Review

on:
  pull_request:
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          ollama run llama3
          pip install litellm
          pip install openai
          pip install python-dotenv
      - name: Start Ollama Service
        run: |
          # Command to start Ollama service
          # Ensure the service starts in the background
          nohup path/to/ollama-service &
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v44
      - name: List All Changed Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Run Python Script
        id: run_python_script
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Running chatbot.py with files: $changed_files"
          python3 chatbot.py "$changed_files" > script_output.txt
          cat script_output.txt
      - name: Perform Code Review
        id: code_review_suggestions
        run: |
          # Get the response from the script output
          response=$(cat script_output.txt)
          echo "This is the response: $response"
          
          # Here we assume the response is a simple string, not a JSON object
          echo "$response" > code_suggestions.txt
      - name: Add Code Suggestions Comment
        run: |
          cat code_suggestions.txt
          escaped_comments=$(echo "$(cat code_suggestions.txt)" | jq -s -R -r @json)
          curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
            -d "{\"body\":$escaped_comments}"
