name: GPT Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sudo -E sh

      - name: Start Ollama Service
        run: |
          nohup ollama serve &

          # A short pause to ensure the service starts
          sleep 5

          # Verify the service is running
          curl -i http://localhost:11434

      - name: Pull Llama3 Model
        run: |
          ollama pull llama3

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install litellm openai python-dotenv

      - name: Fetch Base Branch
        run: |
          git fetch origin main:main

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: List All Changed Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Create Diffs Directory
        run: mkdir -p diffs

      - name: Get File Diffs
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Generating diffs for: $changed_files"
          for file in $changed_files; do
            git diff origin/main -- $file > diffs/$file.diff
          done

      - name: Run Python Script
        id: run-script
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Running chatbot.py with files: $changed_files"
          python3 chatbot.py "$changed_files"

      - name: Add Code Suggestions Comments
        run: |
          # Read the output and post comments
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          for file in $changed_files; do
            review=$(echo "${{ steps.run-script.outputs
