name: GPT Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sudo -E sh

      - name: Start Ollama Service
        run: |
          nohup ollama serve &

          # A short pause to ensure the service starts
          sleep 5

          # Verify the service is running
          curl -i http://localhost:11434

      - name: Pull Llama2 Model
        run: |
          ollama pull llama2

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install litellm openai python-dotenv

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: List All Changed Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          d
